### ISSUE TITLE
npm -i g pm2 undefined

### ISSUE THREAD

**Issue by termiliya** [anc95/ChatGPT-CodeReview#118]
我不是专业前端，不确定是不是我的NPM版本太旧问题，只是反馈下我的情况
readme文件中的 npm -i g pm2 命令似乎有误
应该是npm install -g pm2

我的环境：
OS: WINDOWS 
ARCH:AMF64 
NPM:8.13.2

**Comment by anc95** [comment]
不好意思，是我写错了哈，`npm i -g pm2`. 是对的
