### ISSUE TITLE
can we exclude auto generated files for code review?

### ISSUE THREAD

**Issue by seaguest** [anc95/ChatGPT-CodeReview#121]
Hi,

We have some auto generated files, I want to skip code review for those files (by regular expression pattern), is that possible?

**Comment by anc95** [comment]
Yes, currently we support the IGNORE environment variable, where the value is the filename. However, it is not very convenient to use. I will change it to support glob matching, and once I implement this change, I will publish it.h and publish this then

**Comment by wwzeng1** [comment]
@seaguest @anc95 Happy to use Sweep to help with this. It writes pull requests using AI. Feel free to look at our repo: https://github.com/sweepai/sweep

**Comment by anc95** [comment]
@seaguest @wwzeng1 
just supported the `IGNORE_PATTERNS` setting, can use regexp to exclude files
