### ISSUE TITLE
Misleading logs encountered

### ISSUE THREAD

**Issue by ificiana** [anc95/ChatGPT-CodeReview#129]
Suggestion: something like "no changes found" seems more helpful
https://github.com/anc95/ChatGPT-CodeReview/blob/main/src/bot.ts#L107C1-L110C8
```ts
      if (!changedFiles?.length) {
        console.log('no target label attached');
        return 'no change';
      }
```

**Comment by anc95** [comment]
Thanks. just fixed in newest release.
