### ISSUE TITLE
 It looks like you need to update your Node.js version.

### ISSUE THREAD

**Issue by huneeJung** [anc95/ChatGPT-CodeReview#138]
message : Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: anc95/ChatGPT-CodeReview@main. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

The anc95/ChatGPT-CodeReview@main action you are currently using uses Node.js 16, but this is no longer supported and you will need to update it to use Node.js 20.

Thank you

**Comment by anc95** [comment]
Thank you. Just release v1.0.12 version changing the node version to 20.
