### ISSUE TITLE
Discrepancy in action/index.cjs After Running npm run build

### ISSUE THREAD

**Issue by chibicco** [anc95/ChatGPT-CodeReview#140]
Hi,

I've noticed that `action/index.cjs` doesn't seem to be updated in line with the latest build, as running `npm run build` produces significant differences. 
This issue seems to impact the action's behavior with draft pull requests in GitHub Actions, leading to unexpected results.

**Steps to Reproduce:**
1. Run `npm run build` locally.
2. Compare the output `action/index.cjs` with the version in the repository.

**Expected:**
- `action/index.cjs` should match the build output to ensure proper action functionality.

**Actual:**
- There's a noticeable discrepancy, potentially explaining why draft PRs aren't handled as expected.

Could this be looked into? Consistency between the build output and the repository version is crucial for draft PR support.

Thanks,

P.S. Apologies if my English isn't perfect. Thank you for your understanding.

**Comment by anc95** [comment]
@chibicco Update the action/index.cjs and release v1.0.13. Thank you for pointing out this.

**Comment by chibicco** [comment]
Thank you for your quick response.
We have confirmed that it works in Draft PR :)
