### ISSUE TITLE
how about openai lib instead of chatgpt api (npm) ?

### ISSUE THREAD

**Issue by 1dennispark** [anc95/ChatGPT-CodeReview#145]
We usally use azure openai api. So, we can't set openai api key for this cr gpt github actions.

I think that we can change from chatgpt api to openai official js library.

How about this opinion? give me comment.

**Comment by anc95** [comment]
Hi, I didn't know that the chatgpt-api is not Compatible with thie Azure OpenAI, I think it's fine to change to the official API lib, will work on this later

**Comment by anc95** [comment]
@1dennispark hi, just changed to official openai library in the newest release
