### ISSUE TITLE
Should close old comments after new commits

### ISSUE THREAD

**Issue by GeorgeXCV** [anc95/ChatGPT-CodeReview#146]
It should close off old comments when new stuff has been pushed, or it gets very very spammy. Just closing off the comments can be way too much. In 8 commits the PR feedback has pushed 23 comments that are all 30-40 lines long.

**Comment by anc95** [comment]
Hi, the GPT will only review the new commits if you push to a opened pr, But I don't think should close the previous review result. To avoid too many comments, you can tag the PR as a draft, then the code review will skip, once it turns ready, will trigger the review for whole commits
