### ISSUE TITLE
本地调试时，用如下环境变量为什么会报错 an "installation" key is missing

### ISSUE THREAD

**Issue by Gijela** [anc95/ChatGPT-CodeReview#150]
环境变量：
<img width="768" alt="image" src="https://github.com/user-attachments/assets/c15e95a5-1df2-4f9e-8330-11463fd003f8">

错误日志：
<img width="861" alt="image" src="https://github.com/user-attachments/assets/59cc24c9-2987-4978-8378-dbbab97edcda">

**Comment by Gijela** [comment]
现在能获取到review的结果，但是无法将结果评论到pr变更文件中，🆘

**Comment by anc95** [comment]
@Gijela 是不是 BOT 没给评论的权限
