### ISSUE TITLE
能否只审核指定路径下的文件修改

### ISSUE THREAD

**Issue by zhanglubin12345** [anc95/ChatGPT-CodeReview#160]
比如unity的开发，只想对c#代码部分进行审核，能不能设置，提交了审核后，只针对特定的目录和特定的扩展名文件进行审核

**Comment by anc95** [comment]
我印象中有这个功能，结果看了下没有，这周末我加一下

**Comment by zhanglubin12345** [comment]
@anc95 感谢

**Comment by anc95** [comment]
@zhanglubin12345 更新了，新增了一个环境变量 `IGNORE_PATTERNS: /node_modules,*.md`

**Comment by zhanglubin12345** [comment]
@anc95 
多谢，我试一下看看

**Comment by zhanglubin12345** [comment]
@anc95 
我看了看代码，这是用文件名来筛选的，是不是应该换成文件的完整路径才对？
`!ignorePatterns.some(pattern => new RegExp(pattern).test(file.filename))`
