### ISSUE TITLE
小白使用求助

### ISSUE THREAD

**Issue by ningboRainbow** [anc95/ChatGPT-CodeReview#25]
![image](https://user-images.githubusercontent.com/92293880/219328833-8fe7017f-9fc8-4895-b8c1-fe7b681661dd.png)
你好，我是一位小开发人员，我看到你这个机器人比较感兴趣，因此我计划做两件事：
1、先体验使用看看这个机器人是如何运行的，因此我按照ReadMe中的描述，选择了 Self-hosting 模式进行安装在一台 linux 服务器上，但是安装过程报错了，在执行第二步的时候 回显是 undefined ，我不知道是否是正常的，在执行第三步的时候就直接报错了，能帮看看是啥原因吗？
2、第二件事就是，我使用的是Gerrit 代码托管平台，我想把你这个机器人改造成我的一个小服务，然后在我往 gerrit 上提交代码的时候，调用改造后的机器人接口，也能实现自动添加 reviewer 的功能，那么我需要具体怎么做，能详细指导一下吗？

**Comment by anc95** [comment]
@ningboRainbow 
1. 根据截图的信息，我还不能推断出是什么原因。你可以去具体的日志里看看。其次 self-hosting 的步骤我没有写全，需要添加一些必要的环境变量，我待会补充一下文档
2. 第二件事流程你说的是对的，你需要找一下 Gerrit 的文档，看有没有相关的 webhook 和 review API 可以使用，然后对代码改造就行

**Comment by ningboRainbow** [comment]
> 

针对问题二，我知道需要使用 gerrit 的 webhook 和 review API，我主要是想让您给指点一下，主要改造你这个代码的哪些地方及配置，恳请稍微详细一点的。感谢🙏

**Comment by anc95** [comment]
@ningboRainbow 
1. [src/chat.ts](https://github.com/anc95/ChatGPT-CodeReview/blob/main/src/chat.ts) 这个模块你可以直接用，这个是平台无关的
2. [src/gitub-actions.ts](https://github.com/anc95/ChatGPT-CodeReview/blob/main/src/github-action.cjs) 这个是适配 github actions 的，你可以删掉
3. [src/bot.ts ](https://github.com/anc95/ChatGPT-CodeReview/blob/main/src/bot.ts ) 这个文件强依赖了 github API 和 probot，你可以删掉重新实现这部分逻辑
