### ISSUE TITLE
Doesn't seem to work when there are a lot of modifications

### ISSUE THREAD

**Issue by exposir** [anc95/ChatGPT-CodeReview#28]

**Comment by anc95** [comment]
@exposir OPEN AI API has a limitation for word count. it's not more than about 5000 bytes. so for the bigger file changes, I omit it and don't review.

**Comment by exposir** [comment]
> @exposir OPEN AI API has a limitation for word count. it's not more than about 5000 bytes. so for the bigger file changes, I omit it and don't review.

GET
