### ISSUE TITLE
Is the LANGUAGE environment variable working properly? I would like to receive code reviews in Korean.

### ISSUE THREAD

**Issue by happydeveloper** [anc95/ChatGPT-CodeReview#37]
Hi there. Thank you for making such a great app, but I would like to get a code review in Korean. 
When I looked at the code in the repo, it seems that I can register the LANGUAGE configuration file and process it in the desired language.

But when I test it several times, the code review message is still written in English only.

It would be helpful if the README.md documentation also described how to set the language.

Thanks.

**Comment by anc95** [comment]
@happydeveloper you are welcome. what value did you set for the variable LANGUAGE. it's expected to be a human language,  You can use `Korean` in your situation

**Comment by happydeveloper** [comment]
I have clearly set the environment variable LANGUAGE to Korean as shown in the attached image, but I am still getting responses in English. Does it work in Chinese?

<img width="960" alt="image" src="https://user-images.githubusercontent.com/931731/224651010-e06fbdfe-ce18-4dc2-ac78-5ce1925828bb.png">

**Comment by anc95** [comment]
@happydeveloper Sorry, I didn't have a solid test on this. my prompt is in English, but added in the final "Answer me in `Korean`", but seems it doesn't work from your feedback.

Let me continue working on this feature, to make the prompt itself written in the destination language, this would be better

**Comment by happydeveloper** [comment]
@anc95 Thanks for creating such a great program, it helps our team a lot in our work. I'd like to take this opportunity to thank you, and I hope you continue to develop it, and I'll close this issue.
