### ISSUE TITLE
关于文件长度限制

### ISSUE THREAD

**Issue by firmianay** [anc95/ChatGPT-CodeReview#38]
看起来该工具是将每个文件单独review，并且直接跳过长度大于4000的文件，是否有更好的方式，比如对总长不超过4000的文件合并review，对超长文件切分review？

**Comment by anc95** [comment]
@firmianay 
长文件是可以分割的，但有个问题就是分割后会导致没个片段的上下文不完整了，这样不利于 review，再就是考虑到提代码时候有可能无意间提交一些超大文件，如不小心提交了 node_modules(js), 或者 golang 仓库里一般会把 vendor 提交上去，这些第三方包是不用 review 的，但依赖用户去配置哪些目录要不要review是有风险的，因为一不小心把大且多的文件review了，这都是很烧钱的

可能得等 ChatGPT token 取消限制我们再做优化了

**Comment by hax** [comment]
可以配置吗？比如配置成用 GPT4 然后可以指定最大长度。

**Comment by anc95** [comment]
@hax 支持设置环境变量 `MODEL` 设置模型，但还没支持最大长度参数，可以加一下。(不过真的有人会用 GPT4 review 代码吗，烧钱啊

**Comment by anc95** [comment]
增加了 `max_tokens` 和 `MAX_PATCH_LENGTH` 参数， 可以结合 `gpt-3.5-turbo-16k` 对更长的文本做 review 了
