### ISSUE TITLE
Language is not support

### ISSUE THREAD

**Issue by headless-kjh** [anc95/ChatGPT-CodeReview#39]
yaml
-------
name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Chinese

-------
run
-------
Bellow is the code patch, please help me do a brief code review, if any bug risk and improvement suggestion are welcome
    class ElasticQueryServiceImpl(
 
     override fun addSplitListQuery(value: String?, fieldName: String): BoolQueryBuilder? {
         if (value.isNullOrEmpty()) return null
       val codes = listOf(value.split(",".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray())
        val codes = value.split(",".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
         val boolQueryBuilder = QueryBuilders.boolQuery()
         codes.forEach { boolQueryBuilder.should(QueryBuilders.matchQuery(fieldName, it).operator(Operator.AND)) }
         return boolQueryBuilder

code-review cost: 4.652s
gpt cost: 5.9

-------
result
--------
!

Code Review:

The code looks generally good. The changes made are valid and the logic is sound.

However, there is one small bug risk I see. The listOf() function creates an immutable list, but the code expects to modify it, so it should be changed to a mutable list. Also, the value.split() returns an array of strings, so the codes variable should be declared as an array instead of a list.

Overall, the code looks good and should work as expected.

**Comment by anc95** [comment]
@headless-kjh Hi, It's a known issue. will try to solve this ASAP

**Comment by anc95** [comment]
@headless-kjh It was fixed
<img width="998" alt="image" src="https://user-images.githubusercontent.com/13167934/225493322-3955abc6-441d-403a-8b63-87d2b4489f07.png">

**Comment by headless-kjh** [comment]
Thank you! for quickly resolving the issue!
