### ISSUE TITLE
Ask for asnwer, pls help me 

### ISSUE THREAD

**Issue by maronghe** [anc95/ChatGPT-CodeReview#48]
Seems you are using me but didn't get OPENAI_API_KEY seted in Variables/Secrets for this repo. you could follow [readme](https://github.com/anc95/ChatGPT-CodeReview) for more information

Could you let me know, why my github demo project still get the message?

**Comment by anc95** [comment]
you are using GitHub action or GitHub app?

**Comment by maronghe** [comment]
Is GitHub app meaning that add
```
- name: ChatGPT CodeReviewer
  uses: anc95/ChatGPT-CodeReview@v1.0.3

```
into a .yml file ?

**Comment by anc95** [comment]
No. This is GitHub action. You should set the OPENAI_API_KEY in secrets, and then pass it as an env var in the yml file

**Comment by kocat53** [comment]
@maronghe 

Based on my understanding, it seems like you can just follow the instructions in the image below and ignore the parts listed in the install.

![image](https://user-images.githubusercontent.com/20110150/226557638-193b1bd6-0e49-43e9-b024-6de5eae6b932.png)

**Comment by maronghe** [comment]
ok let me try

**Comment by yimelia** [comment]
hi @anc95 
I set the OPENAI_API_KEY in secrets, and add cr.yml in my commit, like this:

![image](https://user-images.githubusercontent.com/6896468/226841283-415f4117-dc33-48b8-af72-046335c15023.png)

https://github.com/AirtestProject/Airtest/pull/1114/files

still got 
![image](https://user-images.githubusercontent.com/6896468/226841406-abc81f9b-ba03-438c-8d5a-10532ff58b94.png)

Is it because my yml file has not been merged into the master branch yet? （目前的.github/workflow文件夹只推送到了分支上，还没有推送到master）

**Comment by godkor200** [comment]
I have the same problem

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/227092157-a713b0af-2bcc-4536-848a-a6bc85d6d9dd.png)
I had the same issue before, but I have resolved it now. 
 I set the OPENAI_API_KEY in Secrets instead of Variables @godkor200

**Comment by godkor200** [comment]
![스크린샷 2023-03-23 오후 12 17 36](https://user-images.githubusercontent.com/67778293/227093295-194a3a77-8cf4-4406-a19f-90ecba6bb346.png)
I've already set it up, but the same problem is happening.

**Comment by yimelia** [comment]
> ![스크린샷 2023-03-23 오후 12 17 36](https://user-images.githubusercontent.com/67778293/227093295-194a3a77-8cf4-4406-a19f-90ecba6bb346.png) I've already set it up, but the same problem is happening. @yimelia

goto Actions, click `Code Review`, and check if it is empty here?

![image](https://user-images.githubusercontent.com/6896468/227094126-7b6eb44f-5baf-4ec8-a5a0-103ed7b81b17.png)

**Comment by godkor200** [comment]
I solved it. It wasn't a secret, but I added a key to the variables @yimelia

**Comment by anc95** [comment]
If you are using github action, set the key in secret. And if you are using the app, set the key in variable (cause we can't access secret in github app)

**Comment by maronghe** [comment]
Yes. thank you all. I have solved this problem. This is a great CR tool.
