### ISSUE TITLE
安全疑问

### ISSUE THREAD

**Issue by guixin567** [anc95/ChatGPT-CodeReview#51]
想问下会有安全问题吗，chatgpt联网，代码review的时候会有些代码暴露，假如我要把这个引入公司，领导问我这个安全问题，我该怎么回答呢

**Comment by anc95** [comment]
https://help.openai.com/en/articles/7039943-data-usage-for-consumer-services-faq

> Please note that for our API product, OpenAI will not use data submitted by customers via our API to train or improve our models, unless you explicitly decide to [share your data](https://docs.google.com/forms/d/e/1FAIpQLSevgtKyiSWIOj6CV6XWBHl1daPZSOcIWzcUYUXQ1xttjBgDpA/viewform) with us for this purpose.

> 请注意，对于我们的API产品，OpenAI将不会使用通过我们的API提交的客户数据来训练或改善我们的模型，除非您明确决定与我们分享您的数据以实现此目的。

**Comment by guixin567** [comment]
thanks , i see

**Comment by anc95** [comment]
@guixin567 还没有，公司用的 azure 的 repo 😂
