### ISSUE TITLE
装好action之后在提交代码的时候有检测但是没有提示结果

### ISSUE THREAD

**Issue by WXinFfly** [anc95/ChatGPT-CodeReview#59]
![image](https://user-images.githubusercontent.com/25562509/228766538-d06c2a94-58de-46db-b1f0-05e57c03d813.png)
![image](https://user-images.githubusercontent.com/25562509/228766676-57221841-b268-4dd2-aecd-46f1d736a30b.png)

**Comment by WXinFfly** [comment]
你需要什么信息，我可以告诉你 @anc95

**Comment by anc95** [comment]
@WXinFfly 可能是下面两种情况跳过了 Review

1. 文件的 diff 文本过长，超过 GPT 最大 token
2. 文件是 rename 的或者 被 deleted 了

**Comment by WXinFfly** [comment]
> @WXinFfly 可能是下面两种情况跳过了 Review
> 
> 1. 文件的 diff 文本过长，超过 GPT 最大 token
> 2. 文件是 rename 的或者 被 deleted 了

![image](https://user-images.githubusercontent.com/25562509/228770392-68c5ef6c-4cb5-453f-a1a8-7fbde3aac0a4.png)
diff我试了也没有很长，我呢见没有rename货deleted
yml文件是这样的：
![image](https://user-images.githubusercontent.com/25562509/228770754-4cd8fdcd-42d3-41e6-a131-e729bb160f4d.png)
你帮我看一下是不是哪里配置有问题？

**Comment by WXinFfly** [comment]
> > @WXinFfly 可能是下面两种情况跳过了 Review
> > 
> > 1. 文件的 diff 文本过长，超过 GPT 最大 token
> > 2. 文件是 rename 的或者 被 deleted 了
> 
> ![image](https://user-images.githubusercontent.com/25562509/228770392-68c5ef6c-4cb5-453f-a1a8-7fbde3aac0a4.png) diff我试了也没有很长，我呢见没有rename货deleted yml文件是这样的： ![image](https://user-images.githubusercontent.com/25562509/228770754-4cd8fdcd-42d3-41e6-a131-e729bb160f4d.png) 你帮我看一下是不是哪里配置有问题？

@anc95

**Comment by WXinFfly** [comment]
> 没看出什么问题 😭 @WXinFfly

@anc95 已经找到原因了，是因为没有指定gpt的Model

**Comment by WXinFfly** [comment]
@anc95 目前这个项目除了支持PR之外，是否支持正常的push？

**Comment by anc95** [comment]
@WXinFfly synchronize 监听了这个事件就可以

**Comment by WXinFfly** [comment]
@anc95 我指的是直接push，不单独建立一个pullrequest的，是否可以监听？

**Comment by anc95** [comment]
@WXinFfly 不支持的
