### ISSUE TITLE
Action does not properly get triggered upon being integrated with different actions

### ISSUE THREAD

**Issue by mattverse** [anc95/ChatGPT-CodeReview#62]
### Background
I have succeeded in integrating this via github actions with the basic, recommended commands. 

I wanted to take a step further, and make this be triggered only when I have added a specific label to the PR itself. 

https://github.com/mattverse/osmosis/pull/12

This is the sample integration I have been working on. 
Notice that this is almost identical to the original example provided in this repository, the only difference is that it has an if statement for the job to run.

Also notice how the action itself has been properly started, as we can know from run https://github.com/mattverse/osmosis/actions/runs/4604642813/jobs/8135769907?pr=12. 

Would there be specific reason why adding on new logic on top of this gh action might be causing this flakiness?

**Comment by anc95** [comment]
@mattverse Please note that label events do not trigger the review process, but if you attempt to push a new submission after adding a label, it should work as expected and only be reviewed on the specific label tag.

**Comment by mattverse** [comment]
@anc95 Thanks for getting back. Sorry did not quite understand your answer, is there a specific logic in this code base that makes it review only after push of a new commit? Or are you suggesting that there might be something wrong with my github action configuration file?

**Comment by anc95** [comment]
@mattverse Yes, currently the code only responds to the opened and synchronized events and triggers code review.

**Comment by mattverse** [comment]
@anc95 Can you point me to the line of code that has this logic? I can try to pull up a PR to work with any other types as well

**Comment by anc95** [comment]
@mattverse https://github.com/anc95/ChatGPT-CodeReview/blob/main/src/bot.ts#L42. Thank you.
