### ISSUE TITLE
OPEN_API_KEY - Secret vs Variable

### ISSUE THREAD

**Issue by Olshansk** [anc95/ChatGPT-CodeReview#69]
Is there any reason why the OPEN_API_KEY is intended to be a variable rather than a secret? I think the latter would be more secure and achieves the same thing.

**Comment by anc95** [comment]
If you are using Github action way, it is preferable to store `OPEN_API_KEY` as a secret. However, for Github App, accessing the secrets value is forbidden. Therefore, as a workaround, it is recommended to store OPEN_API_KEY in a variable.

**Comment by Olshansk** [comment]
Understood and makes sense. I've removed the app and am only using the workflow now. Thank you for the explanatino!
