### ISSUE TITLE
`OPENAI_API_KEY` not properly detected?

### ISSUE THREAD

**Issue by PeterDaveHello** [anc95/ChatGPT-CodeReview#85]
Got this error from multiple PRs:

> Seems you are using me but didn't get OPENAI_API_KEY seted in Variables/Secrets for this repo. you could follow [readme](https://github.com/anc95/ChatGPT-CodeReview) for more information

(https://github.com/transmission-remote-gui/transgui/pull/1427)

The secret was set as mentioned in the readme, tried both Repository & Organization level:

![image](https://user-images.githubusercontent.com/3691490/236693774-516e0de8-7458-46fe-ab07-12c6db805107.png)

Not sure what's wrong? (I installed from https://github.com/apps/cr-gpt)

**Comment by anc95** [comment]
@PeterDaveHello If you are installing from https://github.com/apps/cr-gpt, please try setting the OPENAI_API_KEY under variables instead of secrets, as a GitHub app is unable to access the secrets value.

**Comment by PeterDaveHello** [comment]
Thanks, it works, not sure if that'll be security concerns that we should be careful?

**Comment by anc95** [comment]
@PeterDaveHello Only the owner of the repo is able to view the variable settings, and since the app does not log or store any information related to the variable, it can be considered secure to a certain extent.

**Comment by PeterDaveHello** [comment]
Okay, thanks!

**Comment by luomanman567** [comment]
I got the same problem...Setting the OPENAI_API_KEY under variables didn't work.
